### ISSUE TITLE
Arrow broken while moving it from one side to another of a tile

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#351] opened 2017-09-13 10:24 UTC
v 106
Hub 84 (and all the other devices)

- Create 2 tiles
- Connect them with the connecting tile
- Move the arrow the other way around (from left to right for example)
- you get a broken arrow (in attach)
![arrow broken](https://user-images.githubusercontent.com/19929395/30372520-6a8a6a46-987e-11e7-89af-50b607d4d18c.jpg)

**Comment by corradocavalli** [comment] 2017-09-14 08:07
This is issue is by design at the moment: The actual implementation doesn't handle all tile positioning like the one in your scenario.

**Comment by gsantopaolo** [comment] 2017-10-26 02:39
yep, by design at the moment... closing

**Closed by gsantopaolo** 2017-10-26 02:39 UTC
Labels: by design, Feature Request
