### ISSUE TITLE
Radial Sub Menu 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#92] opened 2017-02-01 22:26 UTC
1.Activiate Radial Sub Menu (beta)
2.Go to radial Sub Menu
3-Try to create a sticky note
-->No sticky note is generated.

Version: 1.3.5
01.02.2017
23:26
Surface Pro 4

Let me know if we should report issues of features that are in beta.

**Comment by agorog** [comment] 2017-02-02 07:30
If i try to add a tile using mouse click nothing happens. If I click in the middle it goes correctly back to the main menu.

**Comment by agorog** [comment] 2017-02-02 07:35
I noticed the same as @mtg1986 but only the first time at around 8:25 and since then not anymore.

**Comment by agorog** [comment] 2017-02-02 07:38
Adding new tiles is cumbversome if I want to add multiple tiles. After adding a tile the radial menu disappears and to add a new tile you start with main menu, start radial manu and then add tile. The radial add tile menu should stay and not disapper like it is with the square menu and when the user has finished adding tiles it should be possible to close the menu.

**Comment by corradocavalli** [comment] 2017-02-02 08:50
Good point of view, question is 'how'? We have just a single button in the center...

On 2 Feb 2017, at 08:39, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding new tiles is cumbversome if I want to add multiple tiles. After adding a tile the radial menu disappears and to add a new tile you start with main menu, start radial manu and then add tile. The radial add tile menu should stay and not disapper like it is with the square menu and when the user has finished adding tiles it should be possible to close the menu.

-

**Comment by corradocavalli** [comment] 2017-02-02 10:00
There was a regression bug in yesterdays' release, it is now fixed. I've also modified the behavior so that radial menu doesn't automatically revert back to home menu on item selection making it more usable.
Please test it in the new release and provide feedback

**Comment by agorog** [comment] 2017-02-02 17:00
With 1.3.6.0 the radial now dont go back to home. I think it os ok now, you have to call the radial menu, add sticky, call menu again, add sticky, so a bit more work then before, but now it is smooth and in my opionion this is ok now.

**Closed** 2017-02-02 18:41 UTC
Labels: Waiting confirmation
