### ISSUE TITLE
Red Error Message after minizing (v130) - Repro

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#27] opened 2016-11-02 20:54 UTC
@teguria commented on [Mon Oct 31 2016](https://github.com/IBVSoftware/CollaborationHub/issues/183)

New Project -> Open a sticky note -> Minimize Window.
PC: HP Spectre X360
Windows OS: 14393.351
Date: Oct 31, 2016
Time: 07.45, 07.57, 07,58

---

@gsantopaolo commented on [Tue Nov 01 2016](https://github.com/IBVSoftware/CollaborationHub/issues/183#issuecomment-257716681)

same as #186  please test with v133 and let me know if we can close this

**Comment by corradocavalli** [comment] 2016-11-04 09:17
Duplicate of #134, closing.

**Closed by corradocavalli** 2016-11-04 09:17 UTC
Labels: bug
