### ISSUE TITLE
Move connected tile to library / grid library 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#285] opened 2017-08-18 15:19 UTC
Version 1.3.100 Surface Hub

Add grid library, add 2 sticky notes. connect the 2 sticky notes. move one sticky note to grid library. the connecting line stays displayed pointing to nowhere. When moving the sticky note of the grid library it is not connected any more. Proposal for this version: Delete the connections when a tile is moved to a grid library / library, inform user that connection will be lost and if he wants to continue.

**Comment by corradocavalli** [comment] 2017-08-18 16:25
Regression fixed in v101, now connections are removed when a tile is dropped in a Library/GridLibrary
Dialog not added yet since it impacts all the tiles

**Closed** 2017-10-30 16:34 UTC
Labels: Waiting confirmation
