### ISSUE TITLE
Sticky Note Full Screen - Content not full visible

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#352] opened 2017-09-14 07:58 UTC
Surface Hub
Project Code: 8964
Project Key: bu3qu

I created this project on the Surface Hub. Made the Sticky Note Fullscreen and started Inking. 
![impact hub 1](https://user-images.githubusercontent.com/25382402/30418408-24c731aa-9933-11e7-9717-879122d8b912.jpg)

Saved and closed the Project. 

HP Spectre
I opened the Project on my Device. Made the Sticky Note I inked on Full Screen. On my device the content on the Sticky Note is not full visible. 
![unbenannt](https://user-images.githubusercontent.com/25382402/30418387-0df1b75c-9933-11e7-9b4d-1385bf1b00c0.JPG)

**Comment by corradocavalli** [comment] 2017-09-14 08:04
Hi Tamara,
This is by design: The sticky note does not resize its content so when you make it full screen on Hub, since it has a greater resolution than HP Spectre, you're indeed acting on a 'larger' tile, that's why you see more content compared to doing the same on HP machine.

**Comment by tamarawasser** [comment] 2017-09-14 08:09
Okay, so it's more a feature request than an issue? I can make the Sticky Note bigger on my HP, than I'm able to see the content. But the other way, resize its content, would be more nice.

**Comment by corradocavalli** [comment] 2017-09-14 08:12
Close this issue and open a new one labeled "Feature request" with your "nice to have" request :-)

**Comment by gsantopaolo** [comment] 2017-11-30 09:08
closing it because it its already described into the bd fds as development to do as @tamarawasser  described

**Closed by gsantopaolo** 2017-11-30 09:08 UTC
Labels: Feature Request
