### ISSUE TITLE
Notification Hub error while Editing tiles

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#350] opened 2017-09-13 10:16 UTC
v 108
HP Spectre
12.05 p.m.

Project Code: 9189
Project Key: 5m60y
Project description: Test

- double click on the picture with the river
- tap and hold the blue point
- pull it to the Video on the right side (Tiles were connected)
- tap and holt the arrow to get in edit mode
- enter edit mode
- choose red
- choose value 20
- choose route connection than the message appears

Tried again, unable to reproduce

**Comment by teguria** [comment] 2017-09-13 10:17
Tamara had this issue, I'll add her as a member

**Comment by corradocavalli** [comment] 2017-09-14 08:08
We have investigated yesterday afternoon in the telemetry and spotted what could be the cause of the issue, it should (hopefully) fixed in v109.

**Closed** 2017-10-30 16:03 UTC
Labels: Waiting confirmation
