### ISSUE TITLE
Issue with Voice Commands

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#276] opened 2017-08-14 14:01 UTC
We tried all voice commands and get always the answer "Can't do this right now". 

Version 1.3.99.0 
Tested on Surface Hub

**Comment by corradocavalli** [comment] 2017-08-16 09:03
Voice commands were broken due to a regression, they're back with build 100, closing since it is a duplicated of issue #245

**Closed by corradocavalli** 2017-08-16 09:03 UTC
