### ISSUE TITLE
Problems with Zoom Feature on Personal Devices

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#274] opened 2017-08-14 13:29 UTC
After logging in to a project, zoom in and out of the canvas does not work anymore. It is reproducable on these machines. It it is not happing all the time. Seems to be random.

Tested on: 
Think PAD
China Table 
Dell Laptop 

Version 1.3.99.0

**Comment by corradocavalli** [comment] 2017-08-14 14:09
On these machines only? How do you zoom? (Touch, mousewheel)
Please provide a repro scenario, i've tested it thousand times these days with.my machines.
Thanks.

On 14 Aug 2017, at 15:29, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


After logging in to a project, zoom in and out of the canvas does not work anymore. It is reproducable on these machines. It it is not happing all the time. Seems to be random.

Tested on:
Think PAD
China Table
Dell Laptop

Version 1.3.99.0

**Comment by corradocavalli** [comment] 2017-08-17 11:54
Tried both mouse and touch mode with my machines and  zooming works fine with both, what about Surface or other models machines?

**Comment by corradocavalli** [comment] 2017-08-21 16:24
Fixed in v102

**Closed** 2017-08-30 22:47 UTC
Labels: help wanted
