### ISSUE TITLE
Out-of-Sync device

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#345] opened 2017-09-13 09:17 UTC
v 106
Surface Hub 84
Device goes out of sync when connection is slow (all the other devices are in sync, including the ones who are on a different network)

**Comment by corradocavalli** [comment] 2017-09-14 08:10
We discovered the cause of general out of sync issues, unfortunately is out of our radar and we're now trying to understand how we can fix it.

**Comment by gsantopaolo** [comment] 2017-11-30 02:17
Closing, too old

**Closed by gsantopaolo** 2017-11-30 02:17 UTC
Labels: bug, Pending, to investigate
