### ISSUE TITLE
Red error message after switching from one app to another (v134)

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#30] opened 2016-11-04 07:19 UTC
The same issue I had with my laptop still exists with this version.
I create a new project -> Open a Sticky Note -> switch to another app (or minimize CollaBoard) -> back to CollaBoard. I get the red error message
Date and time: Friday, the 4th of November. Time: 08.15 a.m.
Device: HP Spectre x360
Location: Genoa
OS: Windows 10 Enterprise version 1607 (build 14393.351)

**Comment by corradocavalli** [comment] 2016-11-04 07:53
134 had a bug (now fixed) that causes the app to crash on resume after opening/closing the photo camera tile.
Just checked with Ale now and he confirmed that his crash is caused by that bug.
Not sure it happens on all machine, please check.


On 4 Nov 2016, at 08:19, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


The same issue I had with my laptop still exists with this version.
I create a new project -> Open a Sticky Note -> switch to another app (or minimize CollaBoard) -> back to CollaBoard. I get the red error message
Date and time: Friday, the 4th of November. Time: 08.15 a.m.
Device: HP Spectre x360
Location: Genoa
OS: Windows 10 Enterprise version 1607 (build 14393.351)

**Comment by corradocavalli** [comment] 2016-11-04 07:53
134 had a bug (now fixed) that causes the app to crash on resume after opening/closing the photo camera tile.
Just checked with Ale now and he confirmed that his crash is caused by that bug.
Not sure it happens on all machine, please check.


On 4 Nov 2016, at 08:19, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


The same issue I had with my laptop still exists with this version.
I create a new project -> Open a Sticky Note -> switch to another app (or minimize CollaBoard) -> back to CollaBoard. I get the red error message
Date and time: Friday, the 4th of November. Time: 08.15 a.m.
Device: HP Spectre x360
Location: Genoa
OS: Windows 10 Enterprise version 1607 (build 14393.351)

-

**Comment by corradocavalli** [comment] 2016-11-04 09:17
Fixed in v135, please check with that version and reopen if still present.

**Closed by corradocavalli** 2016-11-04 09:17 UTC
