### ISSUE TITLE
Exporting an edited doc file on Hub

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#518] opened 2018-02-27 08:39 UTC
v 2.0.13
Hub + 2 laptops (Spectre and Surface 3)
I was demoing CB and wanted to show the exporting feature on a Word document. Edited the document, saved it and, as long as I save it on CB, I clicked on the export icon and I got a generic error message and the project has been closed.

Not able to reproduce yet.

**Comment by mtg1986** [comment] 2018-07-20 12:54
Tested again with 2.0.41 and we cant reproduce it with a clear scenario. Closing this bug.

**Closed by mtg1986** 2018-07-20 12:54 UTC
Labels: Not Reproducible
