### ISSUE TITLE
Double tab on arrow changes color

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#348] opened 2017-09-13 10:04 UTC
v 106 and 108
2 Hubs

Project Code: 9189
Project Key: 5m60y
Project description: Test

- Create a sticky note
- Upload a couple of more tiles
- Add connecting tiles and connect them all
- Double tab (or single tap) on the arrow will cause it to change color
- Also, all the others in the project won't see the color change

**Comment by corradocavalli** [comment] 2017-09-15 06:11
Fixed in v109.

**Comment by teguria** [comment] 2017-09-19 18:17
Still happening on v 110 (tested yesterday on 2 Hubs - 55 and 84)

**Comment by corradocavalli** [comment] 2017-09-22 04:53
Are you sure that connection doesn't get selected instead (it turns colored magenta) that's the behavior I see on my Surface.

On 19 Sep 2017, at 20:17, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


Still happening on v 110 (tested yesterday on 2 Hubs - 55 and 84)

**Comment by tamarawasser** [comment] 2017-10-30 16:14
@corradocavalli when I tap the arrow than it's selected and color change to magenta, is that right? It happen on all devices. When I tap again it becomes blue again. So it's not a bug, right?

**Comment by corradocavalli** [comment] 2017-11-01 09:42
@tamarawasser yes, that's how it should work, you can close this.

**Closed** 2017-11-01 09:50 UTC
Labels: Waiting confirmation
