### ISSUE TITLE
Erease Ink with backside of Pen on Surface Hub - Panda

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#270] opened 2017-08-14 09:24 UTC
1.Ink on any tile
2.Try to erase Ink on this tile using the back of the pen
3.-->Panda appears 

Is reproducable 

Version 1.3.99 
Tested on Surface Hub 
14.08.2017 11:23

**Comment by corradocavalli** [comment] 2017-08-14 09:43
Ok, this is a regression introduced with the new toolbar, it should be very easy to fix.
FYI: The pen you use to tap the toolbar button is used to configure the toolbar panel with the same previous configuration at opening. And ink panel selection is applied to the pen used to tap the Apply button. If you use finger to tap Apply or open the ink toolbar panel, since we can't detect to which pen apply the selection we apply to all the pens. It is a little bit cumbersome but it was the only way to achieve multiple pen with different attributes working on the same tile on Hub.

On 14 Aug 2017, at 11:24, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


1.Ink on any tile
2.Try to erase Ink on this tile using the back of the pen
3.-->Panda appears

Is reproducable

Version 1.3.99
Tested on Surface Hub
14.08.2017 11:23

**Comment by gsantopaolo** [comment] 2017-08-14 14:13
@corradocavalli honestly i don't like that. please remember me to discuss pen behavior when you'll be back

thanks.

**Comment by corradocavalli** [comment] 2017-08-16 10:40
Fixed with v100, please check it with Hub and close if ok.

**Closed** 2017-08-21 14:27 UTC
Labels: Waiting confirmation
