### ISSUE TITLE
Tile to full screen does not work propery

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#628] opened 2018-07-30 13:41 UTC
Like we experienced in the meeting 30-7-2018

**Comment by corradocavalli** [comment] 2018-07-31 07:17
Can you please describe it better?

**Comment by corradocavalli** [comment] 2018-07-31 08:57
I have tried several times but can't reproduce it, closing and reopen if i raises again.

**Closed by corradocavalli** 2018-07-31 08:57 UTC
Labels: bug
