### ISSUE TITLE
CollaBoard Login Screen on Surface Hub

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#269] opened 2017-08-14 09:09 UTC
When we start the new testing version on the Surface Hub, the same login Screen as on a personal device appears. 
After log-in we have the multi-user and  multi-ink capabilitites. 

Do not know if this is on purpose that we now are forced to log-in on the Surface Hub. 

Tested on: 
Version 1.3.99.00
Surface Hub 
14.08.2017 11:07

**Comment by corradocavalli** [comment] 2017-08-14 09:13
Yes, is by design now.
We have unified the experience between pc and hub, so you get all thr benefits (admin, joined projects...)
Please verify that after closing Hub session you are required to login next time.


On 14 Aug 2017, at 11:09, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


When we start the new testing version on the Surface Hub, the same login Screen as on a personal device appears.
After log-in we have the multi-user and multi-ink capabilitites.

Do not know if this is on purpose that we now are forced to log-in on the Surface Hub.

Tested on:
Version 1.3.99.00
Surface Hub
14.08.2017 11:07

**Comment by gsantopaolo** [comment] 2017-08-14 13:05
On moment please, I've to review this.

thanks all
-g

**Comment by gsantopaolo** [comment] 2017-08-14 13:18
Ok, I reviewed the login functionality and i believe somewhere there was a big misunderstanding.

On the Surface Hub (team family) we do want to allow user to log in because this can hel in some particlar case.
it is mandatory that CollaBoard on Team devices can work as a team, collaborative software, in other workds to work without any authentication.

To solve that challenge we need to add a button "start working" ( @mtg1986  please help with the right label text) thanks to this button users can use collaborad on a surface hub (team device) like before without authenticating. 
Then we also need to allow users to login, and the functionality as it is right now is ok (we need to check if the UX has to change).

thank you
-g

**Comment by mtg1986** [comment] 2017-08-15 07:06
Suggestions for Button Text: 

-Use Personal Edition (Login)
-Use Team Edition (No Login) 

Start working 

-with Personal Edition (Login)
-with Team Edition (No Login)

**Comment by corradocavalli** [comment] 2017-08-18 07:40
Here's login page on Surface with build 101, texts can be changed if you prefer other alternatives.
When user logins on a Surface Hub a warn message is displayed to remind him to logout or close session, we need a proper text, probably one similar to the one in Whiteboard.

![image](https://user-images.githubusercontent.com/5617938/29448900-f105a418-83f8-11e7-80e0-c7346425b002.png)

**Comment by mtg1986** [comment] 2017-09-08 04:49
Test is now: Since this is a shared device, don't forget to logout or end session when done. 

New Text proposal: 
Hey, you are working now with your personal edition of CollaBoard on a Team device. Please make sure to logout at the end of your session, so the next team device user cannot access your projects."

**Comment by corradocavalli** [comment] 2017-09-08 05:07
@gsantopaolo Confirm that is ok so that i can proceed with the change.

**Closed** 2017-11-30 02:44 UTC
Labels: Waiting confirmation
