### ISSUE TITLE
Photo out of the canvas

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#37] opened 2017-01-19 17:45 UTC
1.Taking a photo
2.Throwing it with a lot of power away, photo moves out of the canvas and can not be touched anymore. 
Version 1.2.6
Project Key and Code and Time unknown

**Comment by gsantopaolo** [comment] 2017-01-27 12:05
Thanks, we know where the issue is, we need the time to fix it. we will inform when this will be fixed

**Comment by gsantopaolo** [comment] 2017-01-28 15:15
thanks closing because we already have #39

**Closed by gsantopaolo** 2017-01-28 15:15 UTC
