### ISSUE TITLE
Connecting Tile

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#594] opened 2018-05-24 14:34 UTC
If you connect one tile to another one to the right, you see the connection between them. If you take the tile on the right and pull it to the leftside of the connected tile, so 180 degrees turn to the other side, the connection isn't visible anymore.

Also, if a tile is pinned to the canvas, you can connect FROM the pinned tile, but not from another one TO the pinned tile.

Tested on Surface Hub, Version 2.0.24

**Comment by corradocavalli** [comment] 2018-05-24 14:50
closing since duplicate of #593

**Closed by corradocavalli** 2018-05-24 14:50 UTC
Labels: bug
