### ISSUE TITLE
Dropping lots of images on the canvas

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#308] opened 2017-09-04 18:18 UTC
I've two users connected to the same project from a pc lots of images are dropped to the canvas at the same time
On the other machine i'm able to see times coming with the loading panel
Even waiting 10 or more minutes images are not loaded, tiles stays with the loading panels.
By closing the project and reopening it images are shown

**Comment by corradocavalli** [comment] 2017-09-07 06:26
This is a longtime pending architectural problem, discussed and always postponed.
At the moment upload of a tile tied to a file (image/pdf/Video...) involves too many moving parts and each one is highly critical for the entire process.

Example
1: Client sends PostNew to inform clients that a tile must be shown with busy message
2: Clients upload the file to Azure
3: Client sends PostUploaded, remote clients get informed and image displayed
4:If upload fails, we handle it and client is deleted from the project.

The problem is that if PostUploaded is for any reason not received by the server the tile is kept in pending state **forever** this also happens if, for whatever reason, PostUploaded is not received by remote clients.

This implementation is too weak for several reasons:
1: if the app crashes pending tiles remains in perennial "loading" state.
2: If app suspends during upload the entire sequence is broken and when app resume server return PostDBUnlock error.

We need to move to a single WebAPI call that passes images stream and tile related information to server, uploading, messaging and fault handling must be handled server side, this way we can guarantee that whatever happens new and old clients are kept in sync with tile uploading status.

**Comment by gsantopaolo** [comment] 2017-09-07 12:06
Do you want to send tile content on a stream via rest call?
This means that you have to send tile content's via json object trough network. From the solution we have right is it means to go a tent of years back in development, we would need to:
1. create a state machine for chunking tile content (pretty sure you can't send a 10mb picture on on request)
2. handle chunking and encryption both client and server side
3. handle a state machine on the client an one on the server
4. verify upload errors with retry
5. file checksum before and after sending

on the solution we have right now  we do have all this free thanks to the azure storage api 

IMHO not applicable to our scenario, need to find a different solution...

**Comment by corradocavalli** [comment] 2017-09-07 14:43
No, I mean something more simple like in this example, I have invoked APIs like this several times in projects I worked in the past.
http://www.c-sharpcorner.com/article/upload-and-save-multipartform-data-in-webapi-2/

**Comment by gsantopaolo** [comment] 2017-09-08 10:48
@corradocavalli  to answer your style, No, I don't think this is good.

**Comment by corradocavalli** [comment] 2017-09-08 13:57
Ok, if you have others ideas let's discuss, this is a weakness we need to fix.

**Comment by gsantopaolo** [comment] 2018-02-19 18:29
@corradocavalli we need to discuss this next time youl'll be in zurich

**Comment by corradocavalli** [comment] 2018-05-29 11:43
Too old, closing.

**Closed by corradocavalli** 2018-05-29 11:43 UTC
Labels: To be tested in Zurich, bug, high priority, to investigate
