### ISSUE TITLE
Hub only - Info Menu

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#324] opened 2017-09-12 08:09 UTC
v 1.3.106

Click (or use voice commands) on Info
- Click on on it multiple times
- You get multiple Info windows (in attach)
![wp_20170912_10_06_16_pro](https://user-images.githubusercontent.com/19929395/30314899-770f5d8a-97a2-11e7-9ae3-b3982abb7b41.jpg)

**Comment by corradocavalli** [comment] 2017-09-12 08:11
This is by design, please Close it.

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: alead<mailto:notifications@github.com>
Inviato: Tuesday, September 12, 2017 10:09 AM
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: [IBVSoftware/CollaBoard-Feedback] Hub only - Info Menu (#324)


v 1.3.106

Click (or use voice commands) on Info

  *   Click on on it multiple times
  *   You get multiple Info windows (in attach)
[wp_20170912_10_06_16_pro]<https://user-images.githubusercontent.com/19929395/30314899-770f5d8a-97a2-11e7-9ae3-b3982abb7b41.jpg>

**Closed** 2017-09-12 15:11 UTC
Labels: Waiting confirmation
