### ISSUE TITLE
Size of the pen is not recognized all the time

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#402] opened 2017-10-31 15:11 UTC
HP Spectre
31.10.2017 / 16:00

Create a sticky note
Make it fullscreen
Choose pen and color red, size of the pen is 8
Ink
Change color to blue
Click on the icon with the waves to change the size. 
Change the size by click on the size-regulator
Try to ink – inking is not working – preview with the size and color disappear
Try to ink again – inking is working but with the size the pen had before and not with the size I chooed. 
Click on the icon with the waves again
Change the size again, by pulling the size-regulator with the mouse
Preview with the size and color disappear directly
Inking in the right size and color is working

![size 8](https://user-images.githubusercontent.com/25382402/32231509-11ca0800-be56-11e7-946a-5f7c573fb35b.JPG)

**Comment by corradocavalli** [comment] 2017-10-31 17:55
@tamarawasser  Fixed in v 1.4.4 (note: when changing pen size by clicking instead of dragging the first tap of the pen will cause slider panel to close so inking will be possible by second tap on surface (canvas or tile). This is by design.

**Closed** 2017-11-01 09:05 UTC
Labels: bug, Waiting confirmation
