### ISSUE TITLE
Order in Grid Library

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#236] opened 2017-05-04 09:53 UTC
Project: 1990
Key: c83cr
Time: 11:37am

5 people work on different devices and move stuff into grid libraries. The order in the grid library is not always the same. Just Andis Device (Surface Pro 4) shows the same order as on the Surface Hub. 

Order on the Surface Hub and on Andis Device
![sh](https://cloud.githubusercontent.com/assets/25382402/25698612/c460eaee-30bf-11e7-936d-d5c8dcc4e7c4.JPG)

Order Marc Keller (Device: hp elite book 8570p=
![marc](https://cloud.githubusercontent.com/assets/25382402/25698656/f789503c-30bf-11e7-96fe-35374c736a42.JPG)

Order Svenja Bucher (Device: Dell)
![dell](https://cloud.githubusercontent.com/assets/25382402/25698686/164a34d2-30c0-11e7-8fde-188c75776547.JPG)

Order Tamara Wasser (Device: HP Spectre)
![tamara wasser](https://cloud.githubusercontent.com/assets/25382402/25698715/3b874a0a-30c0-11e7-9591-fa9cb719eb71.JPG)

**Comment by corradocavalli** [comment] 2017-05-04 10:10
Please try to provide a reproducible scenario that we can investigate.

On 4 May 2017, at 11:53, tamarawasser <notifications@github.com<mailto:notifications@github.com>> wrote:


Project: 1990
Key: c83cr
Time: 11:37am

5 people work on different devices and move stuff into grid libraries. The order in the grid library is not always the same. Just Andis Device (Surface Pro 4) shows the same order as on the Surface Hub.

Order on the Surface Hub and on Andis Device
[sh]<https://cloud.githubusercontent.com/assets/25382402/25698612/c460eaee-30bf-11e7-936d-d5c8dcc4e7c4.JPG>

Order Marc Keller (Device: hp elite book 8570p=
[marc]<https://cloud.githubusercontent.com/assets/25382402/25698656/f789503c-30bf-11e7-96fe-35374c736a42.JPG>

Order Svenja Bucher (Device: Dell)
[dell]<https://cloud.githubusercontent.com/assets/25382402/25698686/164a34d2-30c0-11e7-8fde-188c75776547.JPG>

Order Tamara Wasser (Device: HP Spectre)
[tamara wasser]<https://cloud.githubusercontent.com/assets/25382402/25698715/3b874a0a-30c0-11e7-9591-fa9cb719eb71.JPG>

**Comment by corradocavalli** [comment] 2017-05-05 07:36
Closing since can't reproduce it, please reopen it if you find a reproducible scenario.

**Closed by corradocavalli** 2017-05-05 07:36 UTC
