### ISSUE TITLE
Internet connection missing

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#89] opened 2017-01-30 20:11 UTC
during the demo we had today 01/30/2017 18.00-19.00 (on ale's pc) i got a internet connection missing error but the internet was working. the only way to get back to the app was to close and open again.
please investigate and make so that users don't have to forcibly close the app to continue working...

**Comment by teguria** [comment] 2017-01-31 14:15
I got an error message right now (15.15) on my HP Spectre collaborating with the Hub and 4 other different devices
3346
aish6

**Comment by teguria** [comment] 2017-01-31 15:22
It seems this error message is somehow related to the Internet connection error message:
![wp_20170131_16_10_33_pro](https://cloud.githubusercontent.com/assets/19929395/22471011/63af064a-e7d1-11e6-8f0b-d28fd97219fa.jpg)

**Comment by corradocavalli** [comment] 2017-01-31 15:23
How can this help us?

**Comment by teguria** [comment] 2017-01-31 15:38
Says it has been logged so I assumed you could see that.

**Comment by corradocavalli** [comment] 2017-01-31 20:03
Yes, but most of the times, the info we get from the logs are not enough to spot the issue precisely.

On 31 Jan 2017, at 16:39, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


Says it has been logged so I assumed you could see that.

-

**Comment by corradocavalli** [comment] 2017-02-01 09:29
I made connectivity test more reliable, we now check if a site is really reachable to prevent DNS issues.
Regarding the message i think it appears because dialog is also triggered when SignalR connection is lost/closed/fail. This would explain why you see the message when connection seems ok.
@gsantopaolo how should we handle this? should we make it an error instead? note that dialog disappears automatically when SignalR connection becomes available,

**Comment by gsantopaolo** [comment] 2017-02-01 13:12
@corradocavalli  not my case, if connection is timeout no way to go back in collaboard must cole and open again. please fix this behavior

**Comment by corradocavalli** [comment] 2017-02-02 10:01
If you loose connection CollaBoard is not usable at all so it's correct to be locked out of functionalities. Dialog should close automatically when connectivity resumes, if not it's a bug and it has to be fixed.

**Comment by corradocavalli** [comment] 2017-02-03 17:27
Behavior is now changed, in case of SignalR disconnection you get prompted to reload the project. Connection issue is only for real netowork connection problems.

**Comment by gsantopaolo** [comment] 2017-02-06 18:51
@teguria  we will close this in case of no answer

**Comment by agorog** [comment] 2017-02-08 19:59
1.3.9 is still problem and tiles/ink can be lost. I have two projects where this happened 3708/fnb4z and 3710/n6bto are both empty now. No tiles/ink shown. I did the following open project, add/ink several sticky notes. Disconnect. Message comes (text/layout has to be changed see picture). Minimize CB, reconnect. Make CB bigger again, Message "Project has to be reloaded" will be displayed. Project reloads maybe it first shows some tiles, some with, some without tiles, then all disappear and from then on the projects is always shown without tiles. 


![grafik](https://cloud.githubusercontent.com/assets/19590642/22754832/31d25214-ee41-11e6-9be6-e9e902698328.png)

**Comment by corradocavalli** [comment] 2017-02-10 09:55
Tried but unfortunately can't reproduce. Message layout has been fixed. 
Please try to provide a always reproducible scenario so that we can investigate it better.

**Comment by agorog** [comment] 2017-02-10 10:48
Use the following procedure to reproduce (reprpoduced with 1.3.9.0 3797 / q8rko 10.2. 11:35) : 

Create project or open project 
Add sticky note 
Disable WLAN 
Wait until CollaBoard message comes, minimize CollaBoard
Wait at minimum 2 minutes
Activate WLAN
Maximize CollaBoard
Message from CollaBoard that Server said it has to reload project
Project will be shown empty, no sticky note any more 
Close project / Open Project / Project is empty

**Comment by agorog** [comment] 2017-02-10 16:26
1.3.10.0 10.02.2017 17:25 same as with 1.3.9.0

**Comment by corradocavalli** [comment] 2017-02-13 13:36
@agorog  It should have been fixed now, please test it again when new version will be released.

**Comment by agorog** [comment] 2017-02-14 14:57
1.3.12.0 fixed

**Closed by agorog** 2017-02-14 14:57 UTC
Labels: bug, Waiting confirmation
