### ISSUE TITLE
Panda while using Maps

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#421] opened 2017-11-02 12:12 UTC
Surface Book
02.11.2017 / 13:02

Create a new project
Add sticky notes
Add libraries
Add Grid libraries
Open Search
Search for Zurich
Take a picture out of the map
Take one more picture out of the same map
Take one more picture out of the same map
Panda appears (It seems that there is a problem. We will…)

Tried again to reproduce:
Map of Zurich is open in search
Click multiple time on the camera in the map tile to get out a picture
After around 10 times, Panda appears again (It seems that there is a problem. We will...)

**Comment by corradocavalli** [comment] 2017-11-02 12:14
@tamarawasser Can you please to the same with your machine so that i can see what message appears? thx

**Comment by tamarawasser** [comment] 2017-11-02 12:23
HP Spectre
02.11.2017 / 13:23

did the same on my device
![panda](https://user-images.githubusercontent.com/25382402/32325879-0ac01136-bfd1-11e7-86f5-a63bb7d94a49.JPG)

**Comment by corradocavalli** [comment] 2017-11-02 14:08
@tamarawasser Unfortunately can't reproduce it, let's try again with your machine in the office when possible.

**Comment by tamarawasser** [comment] 2017-11-03 08:02
Tried it on HP Spectre with V1.4.8 and it doesn't happen again. 
Tried it on Surface Book with v.1.4.8 and it happen again
![capture](https://user-images.githubusercontent.com/25382402/32364530-a78548d4-c075-11e7-98a0-678678911b59.JPG)

**Comment by corradocavalli** [comment] 2017-11-03 08:51
@tamarawasser Should be fixed on 1.4.8

**Closed** 2017-11-06 15:39 UTC
Labels: bug, Waiting confirmation
