### ISSUE TITLE
Zooming issues

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#563] opened 2018-05-08 13:02 UTC
Happens randomly when multiple people are working on the same project then on some devices zooming is not possible anymore. 
Restarting the app solves the problem. 

2.0.19
08.05.2019
Surface Pro, Laptop 

-->Never happened on Surface Hub so far

**Comment by corradocavalli** [comment] 2018-05-09 14:16
Zooming is handled by UWP framework, need a reproducible case to investigate it.

**Comment by agorog** [comment] 2018-05-09 14:48
This is reproducable with multiple persons working on a project. There are two problem areas: 
1. After some minutes of working in a project opened by multiple persons, suddenly on some devices the zoom in/out does not work anymore. You have to restart CollaBoard to be able too zoom in/out again. Was not able to reproduce working alone in a project. 
2. If other person is moving tiles to other locations it happens that on your own devices the visible part of the project moves to where the other person did something. This happens randomly, i.e. only sometimes not all the time. After this happens it can be that zoom in/out does not work anymore. 

What is the implemented logic for case 2 ?

**Comment by agorog** [comment] 2018-05-09 14:49
See also #566

**Comment by corradocavalli** [comment] 2018-05-09 15:33
There's no logic for case 2 since canvas position is not synced among users, so case 2 sounds strange to me.
Just as confirmation: Are you sure that when zooming stops working Collaboard doesn't enter for whatever reason into "Finger inking mode" ?

**Comment by gsantopaolo** [comment] 2018-05-17 04:50
@gsantopaolo mention to trigger vsts import

**Comment by corradocavalli** [comment] 2018-05-22 12:12
dupicated of case #566 thus closing as well.

**Closed by corradocavalli** 2018-05-22 12:12 UTC
Labels: More info needed, Not Reproducible, To be tested in Zurich
