### ISSUE TITLE
Tiels at different location - Not congruent with Minimap

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#257] opened 2017-07-21 13:42 UTC
Created a new project, added sticky notes images etc. Working on 3 devices simultanously. 

1.Panda on Surface Pro 4. 
2.Reload Project 
3.Tiles are in different location compared to the other two devices where no Panda appeared. 
4.Minimap shows view how it should be (also on the deivce where it is differnet). So on the surface pro 4 the Minimap is not congruent anymore with the sticky notes. (See images) 
-->Very difficult to reproduce as Panada occured.

Project: 2222
Key: 760w0

Version 1.3.98.0
Devices: Surface Hub, Surface Pro 4, China Tablet
21.07.2017

![image](https://user-images.githubusercontent.com/19570958/28465884-a98f2386-6e2a-11e7-8088-4180748bd3e3.png)
![image](https://user-images.githubusercontent.com/19570958/28465917-c6901fa8-6e2a-11e7-84c0-71041d78a66a.png)

**Comment by mtg1986** [comment] 2017-07-21 13:46
Similar behaviour in this project: 
On the Hub we have 17 tiles, on the person devices only 6 tiles. 

Project Code: 2223
Project Key: xz0nc
Project description: Testing
ibv-collaboard:open?code=2223&key=xz0nc

**Comment by corradocavalli** [comment] 2017-07-21 13:53
Michi,
When you have a Panda, the project is out of sync so there's nothing more to do then reload it, if the same problem happens after reloading I can try to investigate but try to understand that it is virtually impossible to  fix "transient" conditions. So, please, for *every* issue, please try to provide a repro case, if possible, so that we can try to reproduce it and fix it definitively, otherwise apart making note I can't do anything to help you on this issues.

**Comment by corradocavalli** [comment] 2017-07-21 13:54
One note: Please use *reliable* connection, office WiFi is *not*

**Comment by corradocavalli** [comment] 2017-07-25 17:04
Can't reproduce, closing.

**Closed by corradocavalli** 2017-07-25 17:04 UTC
