### ISSUE TITLE
On a Surface Hub, tiles are being duplicated

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#205] opened 2017-04-11 13:03 UTC
![duplicate content](https://cloud.githubusercontent.com/assets/19929395/24910307/9b6bfe44-1ec7-11e7-937e-2234e524f1e2.png)

Project Code: 6140
Project Key: ezbmo
Project description: Ale
Time: 15.00

A customer joined a project I already created, from a Surface Hub, from France. The customer saw everything that I created but, when he tried to move a tile, the tile is automatically duplicated.

Customer has Anniversary Update

**Comment by corradocavalli** [comment] 2017-04-11 13:07
Does this happen to him only or others on same project have the same issue?

**Comment by teguria** [comment] 2017-04-11 13:10
It didn't happen to me but Marina, at some point, couldn't see what the customer was doing.

**Comment by corradocavalli** [comment] 2017-04-11 13:14
Can you try with Marina if the same project is ok for you? Are you using internal beta or official store version?

**Comment by teguria** [comment] 2017-04-11 13:16
Yes, we do it now. We are using the normal version installed from the Store

**Comment by teguria** [comment] 2017-04-11 13:17
Works fine for me and Marina. We need to test it on a SFhub

**Comment by corradocavalli** [comment] 2017-04-11 14:19
That's weird, any chance to try again with the customer?

**Comment by teguria** [comment] 2017-04-11 15:58
No we can't, but we will try to replicate on a Surface Hub

**Comment by agorog** [comment] 2017-04-12 06:42
I had a similar experience with version 61: Project 670 open on Hub and on Surface Pro. Workend and saved tiles on Hub. Then on Surface Pro moved a sticky note, it was duplicated and I could ink and save both differently. Did same with second sticky note, same behaviour. Did not see anything on the Hub. Closed project on Surface Pro, the duplicated sticky notes where not shown anymore. Could not reproduce until now.

**Comment by corradocavalli** [comment] 2017-04-12 08:28
@agorog Project 670 looks empty, are you sure it was projectId:670 that contains duplicates tile?

**Comment by agorog** [comment] 2017-04-12 08:40
670 in prod, not test

**Comment by corradocavalli** [comment] 2017-04-12 09:27
Think we spot the issue, from telemetry look like that project was loaded twice in sequence (few ms of difference) and that has caused all tiles to appear overlapped. Issue is fixed in build 62, give it a test when available.

**Comment by mtg1986** [comment] 2017-04-13 13:29
Could not reproduce this bug anymore.

**Closed** 2017-04-13 13:30 UTC
Labels: Waiting confirmation
