### ISSUE TITLE
Inking Grid Library: CB hangs, has to be closed 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#235] opened 2017-05-04 09:39 UTC
Version 1.3.82.0 
Code: 1990 
Key: c83cr 
Machine ID: f07af071-1541-1de0-5297-41f24db959e8

Date 04.06.2017 11:35 tried to ink title of grid library. Collaboard hangs, has to be closed using x. 

![grafik](https://cloud.githubusercontent.com/assets/19590642/25698228/52ffc7ea-30be-11e7-965c-8bda4ead5a51.png)

**Comment by agorog** [comment] 2017-05-04 09:40
Sometime ink her works, sometime not.

**Comment by corradocavalli** [comment] 2017-05-05 07:28
Closing since can't reproduce it, reopen it if you find a reproducible scenario.

**Closed by corradocavalli** 2017-05-05 07:28 UTC
