### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#465] opened 2018-01-18 07:45 UTC
Device: Surface Pro

1.Star CollaBoard
2.Try to login with all sort of acounts 
3.Login is not possible. 

What can we do to figure out what the problem is. As we cannot login  we do not get the Machine-ID.

**Comment by corradocavalli** [comment] 2018-01-18 08:10
Does the problem appears on that machine only? If you login into One drive using the same user you use on Collaboard foes it work?

On 18 Jan 2018, at 08:45, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


Device: Surface Pro

1.Star CollaBoard
2.Try to login with all sort of acounts
3.Login is not possible.

What can we do to figure out what the problem is. As we cannot login we do not get the Machine-ID.

**Comment by mtg1986** [comment] 2018-01-18 10:18
Yes it is only this Machine. We did not figure out what the problem is... Not sure if it makes sense to invest here time, as it is running on all the others well.

**Comment by corradocavalli** [comment] 2018-01-24 10:45
Closing

**Closed by corradocavalli** 2018-01-24 10:45 UTC
