### ISSUE TITLE
Start Screen: Edit Project Description

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#469] opened 2018-01-24 10:44 UTC
Click on Edit Project description. 

Filed is very small
![image](https://user-images.githubusercontent.com/19570958/35328246-ff60e9c0-00fb-11e8-9993-62c362fde582.png)

**Comment by corradocavalli** [comment] 2018-01-24 14:22
Can't reproduce it, does it happen on all machines?

**Comment by mtg1986** [comment] 2018-01-24 14:34
Tested on Surface Pro 4.

**Comment by mtg1986** [comment] 2018-01-29 13:55
On Surface Hub I do not see this issue, On Surface Pro I still have it. When I click in the filed then it gets bigger. Please see the gif. 
![project description](https://user-images.githubusercontent.com/19570958/35513777-6ad3aede-0504-11e8-93ac-3f621220d1ec.gif)


Version: 2.0.11

**Comment by mtg1986** [comment] 2018-01-29 14:24
Now I was also able to reproduce on the Surface Hub
![image](https://user-images.githubusercontent.com/19570958/35515065-7919df28-0508-11e8-94db-bd3e24540990.png)

**Comment by gsantopaolo** [comment] 2018-01-29 21:09
Same behavior here...

**Comment by corradocavalli** [comment] 2018-01-30 13:37
It should be fixed in the version actually in beta, can you verify it?

![cb](https://user-images.githubusercontent.com/5617938/35568977-0c425dc6-05cb-11e8-82cb-ace406c3eb26.gif)

**Comment by tamarawasser** [comment] 2018-02-09 10:13
@corradocavalli Does not happen on SfPro and SfHub but on HP Spectre.

**Comment by corradocavalli** [comment] 2018-02-09 13:11
I've been able to reproduce it and it is fixed now.

**Closed by corradocavalli** 2018-02-09 13:11 UTC
Labels: Fixed, Waiting confirmation, bug, high priority
