### ISSUE TITLE
Tiles on Hub locked after sync project

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#440] opened 2017-11-21 15:35 UTC
HP Spectre
SfHub 55
21.11.2017 / 16:28
Project Code: 11177
Project Key: mnwcd

HP Spectre:
open search
search for Zurich
click on Image
drag some pictures on the canvas 
looks like this: 
![hp](https://user-images.githubusercontent.com/25382402/33081075-a55cc2a4-ced9-11e7-8d61-0a47bf593e70.JPG)

SfHub:
open settings and sync project
after sync pictures are locked by HP Spectre but on HP Spectre they are not in edit mode
![sfh](https://user-images.githubusercontent.com/25382402/33081159-e04a95b2-ced9-11e7-88f0-39aa02a45a43.jpg)

**Comment by tamarawasser** [comment] 2017-11-23 08:55
@corradocavalli I don't know if this is relevant... I logged in with my personal credentials on the SfHub and uploaded some pictures on my HP Spectre. In this case the pictures on the SfHub are not locked.

**Comment by tamarawasser** [comment] 2017-11-23 11:02
@corradocavalli I continue commenting this bug when something happen again. Here next scenario: In the same project with SfHub and HP Spectre. All tiles are unlocked on both devices. I close the project on the HP Spectre and reopen it. All Word Documents are locked by SfHub. But Word Files on SfHub are not in edit mode. 
![word locked](https://user-images.githubusercontent.com/25382402/33169766-18aa22f2-d046-11e7-9c78-3e59bff0efd1.JPG)

**Comment by tamarawasser** [comment] 2017-11-27 12:28
another scenario with HP Spectre, SfBook and SfHub. all devices in the same project (11256 / fvpne) 

Upload files on HP Spectre
Upload files on SfBook
Upload files on SfHub
all uploaded tiles are not in edit mode and all tiles are not locked. 

Desktop timeout on the SfBook turn on. Turn off desktop timeout and login on the SfBook and CollaBoard project sync automatically. Then tiles are locked but it's not visible by witch device. 
![001](https://user-images.githubusercontent.com/25382402/33266517-428b090a-d376-11e7-859e-73785950ca9d.PNG)
After sync Panda appears
![002](https://user-images.githubusercontent.com/25382402/33266591-89ee72a0-d376-11e7-9897-3e6be06191d4.JPG)

Close CollaBoard on SfBook, open CB again and load project again. 
Tiles are locked by the SfHub now, but tiles are not in edit mode on the SfHub
![001](https://user-images.githubusercontent.com/25382402/33266646-c7270ace-d376-11e7-8d72-959b289d1898.JPG)

move each tile on another place on the SfHub. Now tiles on the SfBook are unlocked
![002](https://user-images.githubusercontent.com/25382402/33266666-d8c4956c-d376-11e7-9626-aad0c41db6d9.JPG)

**Comment by corradocavalli** [comment] 2017-11-29 10:32
@gsantopaolo @kasuken 
I've investigated and looks like that when Syncronization is invoked, LoadProject returns a non empty Guid and so the tile appears locked. I've verified that UploadCompleted passes an empty Guid to indicate that tile is not locked, confirmed by the fact that tile appears unlocked initially.

**Comment by corradocavalli** [comment] 2017-11-29 17:59
@tamarawasser fixed in v 2.0.9

**Closed** 2017-11-30 13:06 UTC
Labels: bug, Waiting confirmation
