### ISSUE TITLE
Drag & Drop Images - Message

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#282] opened 2017-08-17 20:45 UTC
When I Drag and Drop Images the Message "Closing Project appears". With Video it is not the case.
Project is not closed and I can contiue working
Version: 1.3.100
Surface Pro
![closing_project_message](https://user-images.githubusercontent.com/19570958/29432986-c8ea680c-839d-11e7-91ff-d5e6f0e525d6.gif)

**Comment by corradocavalli** [comment] 2017-08-18 05:01
Can't reproduce, can you provide a repro sequence?

**Comment by corradocavalli** [comment] 2017-08-21 15:03
Fixed in v 102

**Closed by corradocavalli** 2017-08-21 15:03 UTC
Labels: help wanted
