### ISSUE TITLE
Error message while closing the project

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#406] opened 2017-10-31 15:58 UTC
HP Spectre
31.10.2017 / 16:55
Project Code: 2874
Project Key: c3zf5

Surface Book
31.10.2017 / 16.55
Project Code: 2875
Project Key: c21mg

On both devices and in both projects:
project was open
open radial menu
click on "close project"
confirm closing the project by click on "yes"
this message appears

![bug](https://user-images.githubusercontent.com/25382402/32234243-8beb3c2a-be5c-11e7-8ab1-d7df49697966.jpg)

Not reproducible right now. It's working now.

**Comment by corradocavalli** [comment] 2017-10-31 16:05
@tamarawasser  Closing since a duplicate of #403 that should be fixed in v 1.4.4

**Closed by corradocavalli** 2017-10-31 16:05 UTC
Labels: bug, Not Reproducible
