### ISSUE TITLE
Red Error Message after switching to another app (v130) - Repro

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#16] opened 2016-11-02 20:44 UTC
@teguria commented on [Mon Oct 31 2016](https://github.com/IBVSoftware/CollaborationHub/issues/184)

New Project -> Open a sticky note -> Switch to another app
PC: HP Spectre X360
Windows OS: 14393.351
Date: Oct 31, 2016
Time: 08.00

---

@gsantopaolo commented on [Tue Nov 01 2016](https://github.com/IBVSoftware/CollaborationHub/issues/184#issuecomment-257716451)

same as #186 please test with v133 and let me know if we can close this

**Comment by corradocavalli** [comment] 2016-11-04 09:18
Duplicate of #134. Closing.

**Closed by corradocavalli** 2016-11-04 09:18 UTC
Labels: bug
