### ISSUE TITLE
Info Tile on Hub using Team Edition

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#289] opened 2017-08-30 22:51 UTC
When I use the team edition on Surface Hub the iInfo tile only contains two slides. The slide to set a background image or to switch project ownership are not displayed. 
Tested with: 
1.3.106 
Surface Hub 
31.8.2017

**Comment by corradocavalli** [comment] 2017-08-31 00:08
It's by design, on Team edition there's no user and so those options are not available.


On 30 Aug 2017, at 18:51, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


When I use the team edition on Surface Hub the iInfo tile only contains two slides. The slide to set a background image or to switch project ownership are not displayed.
Tested with:
1.3.106
Surface Hub
31.8.2017

**Comment by mtg1986** [comment] 2017-09-04 02:57
But this would mean that I cannot get ownership of a project that I created on the Surface Hub and that I cannot load a background image as a template. 

Can we change that, as sometimes it is important to get the ownership of a project, even when created by a team?

**Comment by gsantopaolo** [comment] 2017-09-04 13:56
@mtg1986 @corradocavalli  please, next week, when we will be in ibv hq together please ping me on this thanks

**Comment by gsantopaolo** [comment] 2017-11-30 02:33
@tamarawasser can you please investigate?

**Closed** 2017-11-30 13:09 UTC
Labels: Pending, to investigate
