### ISSUE TITLE
Projects not synced 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#592] opened 2018-05-24 12:48 UTC
1.Multiple devices logged into the project 
2.Each user creates sticky notes
-->People do not see the sticky notes of each other. 

![image](https://user-images.githubusercontent.com/19570958/40486368-5c56e0da-5f61-11e8-80fe-73532f1cb6e6.png)

It is project: We all left the project: 

Project Code: 16112
Project Key: faooe
Project description: A
ibv-collaboard:open?code=16112&key=faooe

2.0.24

**Comment by corradocavalli** [comment] 2018-05-25 09:39
Tried with same project and everything works fine here.
From the picture looks like that two projects are totally unconnected and none of the actions on right side are recorded, in fact if i load the project i don't see any of the tiles present on right, just the one on the left.
I inspected the logs and, for that project, I only see login from Michi, Michelle and Andi but no tile creation logs from Michelle or Andi, so my conclusion is that for whatever reason the action reach the server but they don't get processed.
Since we use SignalR for this, this could happen since we have no feedback that message is processed.

**Comment by mtg1986** [comment] 2018-07-23 13:47
@gsantopaolo : What should we do here, close this bug or try to further investigate it? When it is by design I am not sure if more testing will help.

**Comment by gsantopaolo** [comment] 2018-07-23 14:36
@mtg1986  is this something that happens ALL Times? is it reproducible?

**Comment by mtg1986** [comment] 2018-07-23 14:39
@gsantopaolo : No it happens very seldom and is almost impossible to reproduce with a clear scenario.

**Comment by gsantopaolo** [comment] 2018-07-23 15:10
So my guess is that this happens only when a user disconnects from signalr. Any case when compiled for production CB behaves differently when signalr connection is lost.
@corradocavalli  maybe for next releases when you compile for beta, about SignalR they shall get the same bheavior as for productions when SignalR disconnects...

**Comment by gsantopaolo** [comment] 2018-07-23 15:10
@mtg1986 you shall close this...

**Closed** 2018-07-23 15:30 UTC
Labels: Not Reproducible, SignalR, bug, enhancement

**Comment by corradocavalli** [comment] 2018-07-23 15:31
@gsantopaolo Ok
