### ISSUE TITLE
Choose Camera 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#75] opened 2017-01-29 10:01 UTC
Projekt Code: 1436
Projekt Schlüssel: b9y5e
ibv-collaboard:open?code=1436&key=b9y5e
Version: 1.3.0.0 
Date: 29.01.2017 10:15-10:45

Hub: If I open camera it always activates the right camera. Can we allow to switch the camera or use the auto camera swichting as the Hub is doing it in the camera app itself ? 

Surface Pro4: If I open camera it always takes back camera. If I open the win camera app it is the front camera and I can switch to back camera. Can we have the same behaviour as the camera app or be able to choose the camera ?

**Comment by teguria** [comment] 2017-01-29 19:33
The first part is somehow connected to #82 . I believe the second part is another issue/feature

**Comment by gsantopaolo** [comment] 2017-02-06 19:11
closing because duplicate of #82  you will have this soon!

**Closed by gsantopaolo** 2017-02-06 19:11 UTC
Labels: enhancement
